
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfoftxrgevwkoarduomf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmb2Z0eHJnZXZ3a29hcmR1b21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODMwNzIsImV4cCI6MjA1ODc1OTA3Mn0.rJAeW3MGx4emlDxctaVnd4iUbWpXGxAdaaKzazhN71g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type for read_notifications table since it's not in the generated types
export type ReadNotification = {
  id: string;
  notification_id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}
